create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

create policy "Anyone can join the waitlist"
on public.waitlist
for insert
to anon
with check (true);
